baseURL = "http://aloralabs.com/"
languageCode = "en-us"
title = "Alora Labs"

googleAnalytics = "UA-126455348-1"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
description = "Inovation, ideation, creation, salvation!"

[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Projects"
url = "/#projects"
weight = 20
