baseURL = "http://aloralabs.com/"
description = "Inovation, ideation, creation, salvation!"
languageCode = "en-us"
title = "Alora Labs"
googleAnalytics = "UA-126455348-1"

[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Projects"
url = "/#projects"
weight = 20
