baseURL = "https://aloralabs.com/"
languageCode = "en-us"
title = "Alora Labs"

googleAnalytics = "UA-126455348-1"
enableRobotsTXT = true
disableKinds = ["taxonomy", "section", "taxonomyTerm"]
enableGitInfo = true
inlineImports = true

[build]
writeStats = true

[params]
description = "A Toronto-based development agency that lives at the intersection of hardware and digital, acting as a catalyst for teams bringing products to market."

[imaging]
quality = 100

[[menu.main]]
name = "Portfolio"
url = "/#projects"
weight = 20
