[context.production.environment]
HUGO_VERSION = "0.55"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55"

[[redirects]]
from = "https://aloralabs.netlify.com/*"
to = "https://aloralabs.com/:splat"
force = true

[[redirects]]
from = "https://aloralabs.netlify.com/*"
to = "https://aloralabs.com/:splat"
force = true

[[redirects]]
from = "https://aloraengineering.com/*"
to = "https://aloralabs.com/:splat"
force = true

[[headers]]
for = "*"
[headers.values]
"Strict-Transport-Security" = "max-age=63072000; preload"
"Content-Security-Policy" = "default-src https:"
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"
"X-XSS-Protection" = "1; mode=block"
