[context.production.environment]
HUGO_VERSION = "0.58.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.58.0"

[[redirects]]
from = "https://aloralabs.netlify.com/*"
to = "https://aloralabs.com/:splat"
force = true

[[redirects]]
from = "https://aloralabs.netlify.com/*"
to = "https://aloralabs.com/:splat"
force = true

[[redirects]]
from = "https://aloraengineering.com/*"
to = "https://aloralabs.com/:splat"
force = true

[[headers]]
for = "*"
[headers.values]
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Content-Security-Policy = "object-src 'none'; style-src https: 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Service-Worker-Allowed = "/"

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[build.processing.css]
bundle = false
minify = false

[build.processing.js]
bundle = false
minify = false
